//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterfaces._14._06._2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class locationdevice
    {
        public int id { get; set; }
        public string cihazid { get; set; }
        public string cihazadi { get; set; }
    }
}
